### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/xxx/Diary'

### ISSUE THREAD

**Issue by Silom** [sluedecke/atom-diary#2] opened 2015-12-03 11:35 UTC
[Enter steps to reproduce below:]
1. Install
2. Use

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11
**Thrown From**: [atom-diary](https://github.com/sluedecke/atom-diary) package, v1.0.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/xxx/Diary'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/xxx/Diary'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at Object.module.exports.getCreateDirectories.getCreateDirectories [as getCreateDirectories] (/Users/xxx/.atom/packages/atom-diary/lib/calendar-lib.coffee:93:18)
    at Object.module.exports.AtomDiary.addEntry (/Users/xxx/.atom/packages/atom-diary/lib/atom-diary.coffee:158:16)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-diary:addEntry (/Users/xxx/.atom/packages/atom-diary/lib/atom-diary.coffee:42:88)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:12 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:12 atom-diary:addEntry (atom-pane.pane.active)
     -1:10.8.0 core:cancel (atom-pane.pane.active)
     -1:09.5.0 command-palette:toggle (atom-pane.pane.active)
  4x -1:07.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -1:05.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:04.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:04.0 atom-diary:showProject (atom-pane.pane.active)
     -0:56.4.0 settings-view:open (atom-pane.pane.active)
  2x -0:44.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:44.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -0:42 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.5.0 core:close (atom-text-editor#atom-diary.filePrefix.editor.mini.is-focused)
     -0:02.6.0 command-palette:toggle (atom-workspace.workspace.theme-atom-material-syntax.theme-atom-material-ui.scrollbars-visible-when-scrolling)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 atom-diary:addEntry (atom-workspace.workspace.theme-atom-material-syntax.theme-atom-material-ui.scrollbars-visible-when-scrolling)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "webbox-color"
    ]
  },
  "atom-diary": {}
}
```
### Installed Packages

``` coffee
# User
atom-diary, v1.0.1
atom-jade, v0.3.0
atom-material-syntax, v0.2.6
atom-material-ui, v1.0.4
autocomplete-paths, v1.0.2
file-icons, v1.6.13
git-plus, v5.6.6
git-status, v0.3.3
language-babel, v2.5.3
minimap, v4.16.2
pigments, v0.19.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by sluedecke** [comment] 2015-12-03 16:06
Closed as a duplicate of: https://github.com/sluedecke/atom-diary/issues/1

Please see the other one for upates

**Closed as completed by sluedecke** 2015-12-03 16:06 UTC
